add: レポート編集ページのマークアップ
YoslabEngineers/seminar-report-editor pull request #19
Opened 2024-04-09 04:38 UTC by tkming0916

Co-authored-by: sueCalystegia00
# やったこと
- ページ全体のデザインをマークアップに起こした
Figma: https://www.figma.com/file/dfjQLPTZlmvFVPiDT1vFAe/md-report-editor?type=design&node-id=115%3A431&mode=design&t=rE03UNszkh9Cihwb-1

- 大きく「Editor」と「Preview」の2つの要素に分けて，gridで横2つに並べた
- 画像は<Image>で指定，Iconをimportして利用
- 画面幅に合わせてEditorのツール部分が横スクロールされるようにした

# チェックしてほしいこと
- EditorとPreviewの左右切り替え矢印「⇔」はEditorのヘッダー部分にひっついて動くように実装したつもりだが，他の書き方や適切な書き方があれば教えてほしいです
- Editorの<textarea>が適切に実装できているか（あまり自身ない...）

2024-04-09 07:01 UTC, sueCalystegia00 requested changes
@tkming0916 
全体的によく出来てると思う！
レイアウトが一部崩れてる部分とか修正の提案を書いていったので対応よろしく〜
わからないことはいつでも質問してもらえれば👍

2024-04-09 07:01 UTC, sueCalystegia00 commented on next-app/src/app/edit/page.tsx
> +              <div className='h-full my-3'>
[必須]
子要素側には `flex-grow` をつける

[提案]
親側に `gap` を指定して、こちらから `margin` を外すのはいかが？

```suggestion
              <div className='flex-grow'>
```

2024-04-09 07:01 UTC, sueCalystegia00 commented on next-app/src/app/edit/page.tsx
> +            <div className='p-4  h-full'>
[必須]
`h-full (height: 100%)` は「親要素の高さの100%」になるため、上部のタブの高さも含んでしまい、現状親要素をはみ出してしまっている

<img width="1822" alt="Screenshot 2024-04-09 at 15 35 20" src="https://github.com/YoslabEngineers/seminar-report-editor/assets/52482280/05149650-fe0a-4606-b78f-df7aba029bb5">

こういうときは、親要素に `flex` を指定し、子要素側に `flex-grow` を指定すると、
子要素を「親要素の残ったスペースいっぱいに広げる」ことができる。

```suggestion
            <div className='flex flex-col gap-3 p-4  flex-grow'>
```

2024-04-09 07:01 UTC, sueCalystegia00 commented on next-app/src/app/edit/page.tsx
> +          <div>
[必須]

145行目の対応のために `flex` をつける
```suggestion
          <div className='flex'>
```

2024-04-09 07:01 UTC, sueCalystegia00 commented on next-app/src/app/edit/page.tsx
> +              </div>
[提案]
見た目には問題ないけど、HTMLの構造として考えるとここに記述されてるのは気持ち悪い気がする。
(「エディターとプレビューの入れ替えボタン」と「エディターのツール」が並列関係なのか？)

「エディター全体」と「プレビュー全体」の２つの `div` と並列の階層にあるといい気がする

2024-04-09 07:01 UTC, sueCalystegia00 commented on next-app/src/app/edit/page.tsx
> +            </div>
[必須]
プレビューはゼミレポの完成形が表示されているべき箇所なので、ゼミレポのヘッダー(タイトルとかの枠)は作っておいてほしい。

2024-04-12 08:25 UTC, tkming0916 commented on next-app/src/app/edit/page.tsx
> +              </div>
relativeをeditor側につけるのか，ページ全体のmainにつけるのか，どっちが良きですかね？

2024-04-12 08:35 UTC, sueCalystegia00 commented on next-app/src/app/edit/page.tsx
> +              </div>
今回切り替えボタンを「エディターとプレビューを包含する要素」の直下に階層に配置するなら、その「包含する要素」にrelativeを付けるべきじゃないかな？
切り替えボタンのabsoluteの基準としたい要素にrelativeを付けるイメージ

2024-04-12 08:55 UTC, tkming0916 commented on next-app/src/app/edit/page.tsx
> +              </div>
previewのヘッダーに追従する形なのかなって思ったんですけど，htmlの構造的に気持ち悪いですもんね．．．むじい

2024-04-12 11:12 UTC, sueCalystegia00 commented on next-app/src/app/edit/page.tsx
> +              </div>
エディターとプレビューが常にラッパー要素のwidth50%なら、切り替えボタンもラッパー要素の真ん中にabsoluteで位置指定すれば追従すると思ってたけど違った？

2024-04-13 10:09 UTC, tkming0916 commented on next-app/src/app/edit/page.tsx
> +            <div className='p-4  h-full'>
5ace172d18e84eb06b13a5d68c8cd37c3b4e8789 で修正しました👍

2024-04-13 10:09 UTC, tkming0916 commented on next-app/src/app/edit/page.tsx
> +          <div>
5ace172d18e84eb06b13a5d68c8cd37c3b4e8789 で修正しました👍

2024-04-13 10:10 UTC, tkming0916 commented on next-app/src/app/edit/page.tsx
> +              <div className='h-full my-3'>
7628bb7704477de5f8cb8c438545e84e157b9b29 で修正しました．

2024-04-13 10:10 UTC, tkming0916 commented on next-app/src/app/edit/page.tsx
> +              </div>
90708cde1683c4ab8c143b511d297fe857739fa8 で修正しました．

2024-05-11 04:52 UTC, sueCalystegia00 commented on next-app/src/app/edit/page.tsx
> +            </div>
大枠出来ている。previewのレスポンシブ対応はコンポーネントに切り分けた後に対応できればいいので、一旦OK

2024-05-11 04:52 UTC, sueCalystegia00 approved these changes
LGTM

2024-05-11 04:53 UTC, merged