Feat/#15 Reort新規作成処理
YoslabEngineers/seminar-report-editor pull request #22
Opened 2024-04-12 14:40 UTC by banamon

# {PR title}

## 対応内容・対応背景・妥協点

## やったこと

- 

## やってないこと

- 

## UI before / after

## テストの変更点

- [ ] ある
- [ ] ない

## レビュー観点

- 

## 補足

2024-04-13 08:47 UTC, tkming0916 commented
@banamon @s256270 
.envのサンプルがないんですけど〜〜〜ぉ

2024-04-13 09:11 UTC, s256270 commented
@tkming0916 
[676c3e7](https://github.com/YoslabEngineers/seminar-report-editor/pull/22/commits/676c3e779ccd13de1b3c40096046a68018f69d00) で.envのサンプルを追加しました

2024-04-13 10:03 UTC, tkming0916 requested changes
割と良さげに見えました．
リードーミーだけもうちょいわかりやすく書いたほうがよきかな！

2024-04-13 10:03 UTC, tkming0916 commented on next-app/src/lib/prisma/README.md
> +prismaのコマンド
このコマンドをいつ使うのか？
なんのためのコマンドなのかわからない...
もう少し丁寧に書いてください〜

2024-05-02 09:30 UTC, banamon commented on next-app/src/lib/prisma/README.md
> +prismaのコマンド
aa4ff95
かいたちょ

2024-05-02 14:12 UTC, sueCalystegia00 approved these changes
LGTM

2024-05-11 04:55 UTC, tkming0916 commented on next-app/src/lib/prisma/README.md
> +prismaのコマンド
見た👀

2024-05-12 10:20 UTC, sueCalystegia00 approved these changes
モブプロで見てたのもあるので、大枠問題ないかと

2024-05-13 06:06 UTC, tkming0916 commented
ざっと見ました！
こっちの環境で動かしてみようとしたけど，`npx prisma db pull --schema=./src/lib/prisma/schema.prisma` でenvないのURLがないって言われちゃった🥺

2024-05-13 06:20 UTC, banamon commented
> ざっと見ました！ こっちの環境で動かしてみようとしたけど，`npx prisma db pull --schema=./src/lib/prisma/schema.prisma` でenv内のURLがないって言われちゃった🥺

確認あざす！
.env.local.sample参考に編集してもろたらいけるかと！ディスコに投げとくわ

2024-12-29 04:03 UTC, merged