Feat/#28 add application service
YoslabEngineers/seminar-report-editor pull request #31
Opened 2024-05-11 08:14 UTC by tkming0916

# {PR title}

## 対応内容・対応背景・妥協点

editページに対応するアプリケーション層の作成

## やったこと

- service.tsを作成
- データの取得(getReport)と送信(postReport)を担う関数を実装

## やってないこと

- BEとの足並みは揃えてないので，ダミーデータで実装しています

## UI before / after

## テストの変更点

- [ ] ある
- [ ] ない

## レビュー観点

- URLの取得が適切かどうか
- マージ先はmainで良かったのか...

## 補足

2024-05-11 10:25 UTC, banamon reviewed
レビュワー指名されてないけど，すーさんと開発してそうだったから，もりちと画面共有してレビューしてみました！
軽くみていただけたら嬉しいです

2024-05-11 10:25 UTC, banamon commented on next-app/src/app/edit/page.tsx
>  import ReportPreview from '../_components/ReportPreview'
[質問] フロントが分かってないけど，importは相対パスでかくのが多い感じですか？@を使う時の差があれば聞きたみです🙋🏻‍♂️

2024-05-11 10:25 UTC, banamon commented on next-app/src/app/edit/service.ts
> +export const postReport = async (report: Report, user: User) => {
[imo] ReportってUserを持ってると思うので，引数はReportだけでもいいのかなって思いました！

2024-05-12 04:23 UTC, tkming0916 commented on next-app/src/app/edit/service.ts
> +export const postReport = async (report: Report, user: User) => {
a9c5bb3 で修正しました！

2024-05-12 04:45 UTC, tkming0916 commented on next-app/src/app/edit/page.tsx
>  import ReportPreview from '../_components/ReportPreview'
これは単純にミスです... さーせん by @sueCalystegia00 
レビュー漏れでした... さーせん by @tkming0916 
019fd51 で修正しました．

2024-05-12 04:48 UTC, tkming0916 commented on next-app/src/app/edit/page.tsx
>  import ReportPreview from '../_components/ReportPreview'
同じ階層で他の場所から使われない場合は，相対パスでOKです．他の場所から使われる場合は絶対パスにします．たとえば，_components内の各コンポーネントにあるindex.tsxでは相対パスが使われていますが，page.tsxでインポートする際は絶対パスでコンポーネントを呼び出してます．

2024-05-12 04:51 UTC, banamon commented on next-app/src/app/edit/page.tsx
>  import ReportPreview from '../_components/ReportPreview'
なるほど承知です！

2024-05-12 04:53 UTC, sueCalystegia00 requested changes
ちょっと修正してほしい

2024-05-12 04:53 UTC, sueCalystegia00 commented on next-app/src/app/_domain/model/user.ts
prettierが効いてないように見えるのでformatterかけたほうがいいかも
(もともと効いてなかったのが気になるけど)

2024-05-12 04:53 UTC, sueCalystegia00 commented on next-app/src/app/edit/service.ts
> +}
改行入れて

2024-05-12 05:02 UTC, banamon reviewed
修正あざます！

修正箇所以外の話になって申し訳ないが，postReportの方と同様にgetReportの方も気になったんで，一応書いてます！確認してくれたら嬉しみです！🫡

2024-05-12 05:02 UTC, tagahei commented on next-app/src/app/edit/service.ts
> +  // いったんダミーデータを返します
[imo] 前のporstReportの内容と少し被るけど，Userを定義するのはgetReportの中でやる感じ？？実際のユーザがもういる状態で実行するならpostReport同様に引数にUserなのかなとか思いました！

前回レビュー漏れで申し訳ない

2024-05-12 05:02 UTC, tagahei commented on next-app/src/app/edit/page.tsx
> +  // console.log(report)
[imho] 些細やけ，修正は任せるが，個人的には無駄な行は消す派ですっ！

2024-05-12 05:02 UTC, banamon commented on next-app/src/app/edit/service.ts
> +export const postReport = async (report: Report, user: User) => {
ありがとうううう

2024-05-12 05:04 UTC, tkming0916 commented on next-app/src/app/edit/service.ts
> +}
165a2b2 で修正しました(｀･ω･´)ゞ

2024-05-12 05:04 UTC, tkming0916 commented on next-app/src/app/_domain/model/user.ts
https://github.com/YoslabEngineers/seminar-report-editor/commit/165a2b214a88e903f0610fe518ac46961b6c242c で修正しました(｀･ω･´)ゞ

2024-05-12 05:14 UTC, tkming0916 commented on next-app/src/app/edit/service.ts
> +  // いったんダミーデータを返します
[9d46274](https://github.com/YoslabEngineers/seminar-report-editor/pull/31/commits/9d4627479bcb09d43a77becbe198bb7fda50429a)　で修正しました

2024-05-12 05:14 UTC, tkming0916 commented on next-app/src/app/edit/page.tsx
> +  // console.log(report)
[9d46274](https://github.com/YoslabEngineers/seminar-report-editor/pull/31/commits/9d4627479bcb09d43a77becbe198bb7fda50429a)　で修正しました

2024-05-12 05:16 UTC, sueCalystegia00 approved these changes
LGTM

2024-05-12 05:17 UTC, merged